services:
  php_users:
    build:
      context: ../user-service
      dockerfile: ../user-service/Dockerfile
    volumes:
      - ../user-service/:/var/www/html
      - ../user-service/:/srv/user-service
      - users_storage:/var/www/html/storage
      - users_cache:/var/www/html/bootstrap/cache

  php_products:
    build:
      context: ../product-service
      dockerfile: ../product-service/Dockerfile
    volumes:
      - ../product-service/:/var/www/html
      - ../product-service/:/srv/product-service
      - products_storage:/var/www/html/storage
      - products_cache:/var/www/html/bootstrap/cache

  php_orders:
    build:
      context: ../order-service
      dockerfile: ../order-service/Dockerfile
    volumes:
      - ../order-service/:/var/www/html
      - ../order-service/:/srv/order-service
      - orders_storage:/var/www/html/storage
      - orders_cache:/var/www/html/bootstrap/cache

  web:
    image: nginx:1.28.1
    ports:
      - "80:80"
    volumes:
      - ../user-service:/srv/user-service
      - ../product-service:/srv/product-service
      - ../order-service:/srv/order-service
      - ./nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_users
      - php_products
      - php_orders

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_USER: "cloudshoptuser"
      MYSQL_PASSWORD: "cloudshoptpass"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:8
    volumes:
      - redisdata:/data

volumes:
  users_storage:
  users_cache:
  products_storage:
  products_cache:
  orders_storage:
  orders_cache:
  mysqldata:
  redisdata: