services:
  gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - orders
      - products
      - users

  # ---------- MySQL (shared) ----------
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 20

  # ---------- REDIS ----------
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # ---------- Orders ----------
  orders:
    build:
      context: ../order-service
    volumes:
      - ../order-service:/var/www/html
      - orders_vendor:/var/www/html/vendor
    ports:
      - "8001:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8001

      INTERNAL_TOKEN: ${INTERNAL_TOKEN}
      PRODUCTS_INTERNAL_TOKEN: ${INTERNAL_TOKEN}
      USERS_INTERNAL_TOKEN: ${INTERNAL_TOKEN}

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: orders_db
      DB_USERNAME: orders
      DB_PASSWORD: orderspass

      KAFKA_BROKERS: kafka:29092
      KAFKA_REST_URL: http://kafka-rest:8082
      REDIS_HOST: redis
      QUEUE_CONNECTION: redis
      CACHE_STORE: redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    command: sh -lc "composer install && php artisan serve --host=0.0.0.0 --port=8000"

  # ---------- Products ----------
  products:
    build:
      context: ../product-service
    volumes:
      - ../product-service:/var/www/html
      - products_vendor:/var/www/html/vendor
    ports:
      - "8002:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8002

      INTERNAL_TOKEN: ${INTERNAL_TOKEN}

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: products_db
      DB_USERNAME: products
      DB_PASSWORD: productspass

      KAFKA_BROKERS: kafka:29092
      KAFKA_REST_URL: http://kafka-rest:8082
      REDIS_HOST: redis
      QUEUE_CONNECTION: redis
      CACHE_STORE: redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    command: sh -lc "composer install && php artisan serve --host=0.0.0.0 --port=8000"

  # ---------- Users ----------
  users:
    build:
      context: ../user-service
    volumes:
      - ../user-service:/var/www/html
      - users_vendor:/var/www/html/vendor
    ports:
      - "8003:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8003

      INTERNAL_TOKEN: ${INTERNAL_TOKEN}

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: users_db
      DB_USERNAME: users
      DB_PASSWORD: userspass

      KAFKA_BROKERS: kafka:29092
      KAFKA_REST_URL: http://kafka-rest:8082
      REDIS_HOST: redis
      QUEUE_CONNECTION: redis
      CACHE_STORE: redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    command: sh -lc "composer install && php artisan serve --host=0.0.0.0 --port=8000"

    # ---------------- KAFKA ------------------
    #  zookeeper:
    #    image: confluentinc/cp-zookeeper:7.6.0
    #    environment:
    #      ZOOKEEPER_CLIENT_PORT: 2181
    #      ZOOKEEPER_TICK_TIME: 2000
    #
    #  kafka:
    #    image: confluentinc/cp-kafka:7.6.0
    #    depends_on:
    #      - zookeeper
    #    ports:
    #      - "9092:9092"     # host access (optional)
    #    environment:
    #      KAFKA_BROKER_ID: 1
    #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #
    #      # Internal (Docker network) + External (host)
    #      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
    #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    #      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    #
    #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #
    #  kafka-ui:
    #    image: provectuslabs/kafka-ui:latest
    #    depends_on:
    #      - kafka
    #    ports:
    #      - "8085:8080"
    #    environment:
    #      KAFKA_CLUSTERS_0_NAME: local
    #      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    #
    #  # Optional: Kafka REST Proxy (nice for PHP if you don't want rdkafka extension yet)
    #  kafka-rest:
    #    image: confluentinc/cp-kafka-rest:7.6.0
    #    depends_on:
    #      - kafka
    #    ports:
    #      - "8082:8082"
    #    environment:
    #      KAFKA_REST_HOST_NAME: kafka-rest
    #      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
    #      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29092

volumes:
  mysql_data:
  orders_vendor:
  products_vendor:
  users_vendor:
