{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include (print .Chart.Name ".fullname") . }}
  labels:
    {{- include (print .Chart.Name ".labels") . | nindent 4 }}
    release: {{ .Values.metrics.monitoringRelease | quote }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include (print .Chart.Name ".selectorLabels") . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path | default "/metrics" | quote }}
      interval: {{ .Values.metrics.interval | default "15s" | quote }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout | default "10s" | quote }}
      {{- if and .Values.metrics.bearerToken .Values.metrics.bearerToken.enabled }}
      bearerTokenSecret:
        name: {{ .Values.metrics.bearerToken.secretName | quote }}
        key: {{ .Values.metrics.bearerToken.secretKey | quote }}
      {{- end }}
{{- end }}
